# Generated by Django 4.0.1 on 2022-01-21 20:01

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('delegations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='delegation',
            name='check_start_date',
        ),
        migrations.AddConstraint(
            model_name='delegation',
            constraint=models.CheckConstraint(check=models.Q(('return_date__gte', django.db.models.expressions.F('departure_date'))), name='check_start_date'),
        ),
    ]
