# Generated by Django 4.0.1 on 2022-01-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegations', '0002_remove_delegation_check_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('euro', 'euro'), ('zloty', 'zloty'), ('yen', 'yen'), ('british pound', 'british pound'), ('juan', 'juan'), ('swiss franc', 'swiss franc'), ('czech koruna', 'czech koruna'), ('american dollar', 'american dollar')], default='zloty', max_length=255),
        ),
    ]
